server:
  context-path:
  port: 8081

spring:
  profiles:
    active: dev

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.ys.mvc.dao.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
